let appointments = JSON.parse(localStorage.getItem('acucareAppointments') || '[]');
const rows = document.getElementById('bookingRows');
const empty = document.getElementById('emptyState');
const search = document.getElementById('search');
const branchFilter = document.getElementById('branchFilter');
const statusFilter = document.getElementById('statusFilter');

function save(){localStorage.setItem('acucareAppointments',JSON.stringify(appointments));render()}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateStats(){document.getElementById('totalCount').textContent=appointments.length;document.getElementById('pendingCount').textContent=appointments.filter(a=>a.status==='Pending confirmation').length;document.getElementById('ebeneCount').textContent=appointments.filter(a=>a.branch==='Ebène').length;document.getElementById('plCount').textContent=appointments.filter(a=>a.branch==='Port Louis').length}
function render(){const q=search.value.toLowerCase();const filtered=appointments.filter(a=>(!branchFilter.value||a.branch===branchFilter.value)&&(!statusFilter.value||a.status===statusFilter.value)&&(`${a.id} ${a.firstName} ${a.lastName} ${a.phone}`.toLowerCase().includes(q)));rows.innerHTML=filtered.map(a=>`<tr><td><strong>${esc(a.id)}</strong><br><small>${new Date(a.createdAt).toLocaleDateString()}</small></td><td><strong>${esc(a.firstName)} ${esc(a.lastName)}</strong><br><small>${esc(a.phone)} • ${esc(a.email)}</small></td><td>${esc(a.branch)}</td><td>${esc(a.date)}<br><small>${esc(a.time)}</small></td><td>${esc(a.treatment)}</td><td><select class="status" data-id="${esc(a.id)}"><option ${a.status==='Pending confirmation'?'selected':''}>Pending confirmation</option><option ${a.status==='Confirmed'?'selected':''}>Confirmed</option><option ${a.status==='Completed'?'selected':''}>Completed</option><option ${a.status==='Cancelled'?'selected':''}>Cancelled</option></select></td><td><button class="delete" data-delete="${esc(a.id)}">Delete</button></td></tr>`).join('');empty.style.display=filtered.length?'none':'block';document.querySelectorAll('.status').forEach(s=>s.onchange=()=>{const a=appointments.find(x=>x.id===s.dataset.id);if(a){a.status=s.value;save()}});document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this appointment request?')){appointments=appointments.filter(a=>a.id!==b.dataset.delete);save()}});updateStats()}
[search,branchFilter,statusFilter].forEach(el=>el.addEventListener('input',render));
document.getElementById('exportBtn').onclick=()=>{const fields=['id','firstName','lastName','phone','email','branch','treatment','date','time','message','status','createdAt'];const csv=[fields.join(','),...appointments.map(a=>fields.map(f=>`"${String(a[f]||'').replace(/"/g,'""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='acucare-appointments.csv';link.click();URL.revokeObjectURL(url)};render();
